### ISSUE TITLE
[Experiment] Adding EMA via a custom loop. 

### ISSUE THREAD

**Issue by AdityaKane2001** [AdityaKane2001/regnets_trainer#3]
I have decided to implement custom loop for training with EMA using [tf.train.ExponentialMovingAverage](https://www.tensorflow.org/api_docs/python/tf/train/ExponentialMovingAverage). This will eliminate a big difference between the two implementations.

**Comment by sayakpaul** [comment]
@AdityaKane2001 please be careful while we writing the custom training loop and consult the related tutorials, examples, and guides to understand the mechanics and the factors that can go wrong in this. 

One example is available here: https://github.com/sayakpaul/FunMatch-Distillation/blob/main/funmatch_distillation.ipynb.

**Comment by AdityaKane2001** [comment]
Since our model is straightforward, I don't think there's a need to subclass `Model`. [Here](https://www.tensorflow.org/guide/keras/writing_a_training_loop_from_scratch) they have not subclassed `Model` until necessary. 

Please correct me if I'm wrong.

**Comment by sayakpaul** [comment]
Also, prefer referring to this guide rather than the one you mentioned: https://keras.io/guides/customizing_what_happens_in_fit/.
