### ISSUE TITLE
[Experiment] Using non-resized ImageNet-1k dataset

### ISSUE THREAD

**Issue by AdityaKane2001** [AdityaKane2001/regnets_trainer#4]
Here we redo the TFRecords by _not_ resizing the images to some fixed resolution. We use an input pipeline which is closest to the original implementation.

Run [here](https://wandb.ai/compyle/keras-regnet-training/runs/u3zg0uyj).

**Comment by AdityaKane2001** [comment]
@sayakpaul 

After first [run](https://wandb.ai/compyle/keras-regnet-training/runs/u3zg0uyj): Val acc lags the previous best by 8% throughout the run, whereas train accuracy is same as before.

It makes sense to augment the data more and add some regularization. Thus adding color jitter and mixup to the pipeline. I am inclined towards normalizing the data by ImageNet mean and std, but there's no concrete reason why we should do that, so skipping for it now.

WDYT?

**Comment by sayakpaul** [comment]
The first point sounds good to me. The second one could be optional IMO.
